package com.jaosn.gwtproject.shared.enums;

public enum CrmForm {
	ORDER_LOG, SERVICE_RESERVATION, SLV_REF_LOG, EDM, SIMPLE_REF_LOG, 
	RESOURCE_SHORTAGE, ROLLOUT_CHECKING, _2N_FAST_TRACKING, MOBILE_COVERAGE,
	ACTION_FORM, SVC_ACTION_FORM;
}
