package com.jaosn.gwtproject.shared.enums;

public enum SvcFunctionCode {
	//SVC
	CUSTOMER_SEARCH(56L), 	
	FOLLOWUP_REMINDER(67L),
	CUST_CONTACT_HISTORY(581L),
	CALL_NATURE_ADMIN(71L),	
	SLV_PROFILE(63L),
	MOB_PROFILE(59L),
	IMS_PROFILE(61L),
	LTS_PROFILE(57L),
	CSL_PROFILE(281L),
	CSL_IFE(282L),
	MOB_SERVICE_USAGE(60L),
	LTS_SERVICE_USAGE(58L),
	IMS_TV_VIEWERSHIP(62L),
	HOT_OF_THE_DAY_ADMIN(72L),	
	PROSPECT_CUSTOMER_SEARCH(64L),
	REGISTER_DFORM(69L),
	DFORM_MANAGEMENT(70L),	
	FOLLOWUP_CASE_CREATION(68L),
	INTERACTION_LOG_CREATION(65L),
	SEARCH_INTERACTION_LOG(66L),
	IMPORT_CALL_NATURES(101L),
	QUICK_HELP(73L),
	TEST_PAGE(161L),
	NETWORK_TEST(241L),
	FOLLOWUP_ADMIN(242L),
	EMAIL_ADMIN(522L),
	SEND_EMAIL(523L),
	SMS_ADMIN(524L),
	SEND_SMS(525L),
	EMAIL_SEND_HISTORY(526L),
	SMS_SEND_HISTORY(527L),
	FAX_ADMIN(681L), SEND_FAX(682L),
	MOB_OPTOUT(643L),
	MOB_PAYMENT_UPDATE(661L),
	MOB_MKT_INFO(731L),
	//NA("NA"),
	// SB Order detail
	IMS_SB_ORDER_DETAIL(143L),LTS_SB_ORDER_DETAIL(142L),
	MOB_SB_ORDER_DETAIL(141L),SLV_SB_ORDER_DETAIL(127L),
	NEW_SLV_SB_ORDER_DETAIL(0L),
	//Alert Messages
	IMS_ALERT_MESSAGE(15L),
	IMS_ALERT_MESSAGE_PREMIER(16L),
	LTS_ALERT_MESSAGE(25L),
	LTS_ALERT_MESSAGE_PREMIER(26L),
	LTS_ALERT_MESSAGE_RETAIL_AND_SC(24L),
	MOB_ALERT_MESSAGE(32L),
	MOB_CHANGE_SIM_ALERT(181L),
	//Acq, Retention, Termination
	IMS_RETENTION(19L), IMS_TERMINATION(20L), IMS_ACQ(12L), IMS_BIQ(481L), 
	LTS_ACQ(21L),LTS_RETENTION(29L),LTS_TERMINATION(30L), 
	MOB_ACQ(31L),MOB_RETENTION(34L),
	MOB_SIM_REPLACEMENT(421L),MOB_CHANGE_PAYMETHOD(422L),
	MOB_BILL_MEDIA_UPDATE(683L),MOB_CUST_CONTACT_UPDATE(684L),
	PSG_ADMIN_PORTAL(381L), PSG_CASH_TOPUP(401L), PSG_KYC(521L),
	SLV_CUSTPROFILE(49L), SLV_SERVICEPROFILE(63L), SLV_ACQ(76L), SLV_ALERT_MESSAGE(202L),
	NEW_SLV_CUSTPROFILE(0L), NEW_SLV_SERVICEPROFILE(0L), NEW_SLV_ACQ(482L), NEW_SLV_ALERT_MESSAGE(0L),
	PREPAID_WEBLINK(622L),
	NOW_ACQ(111L), NOWTV_RETENTION(721L),
	CLUB_CAMPAIGN(701L),
	// Change Shop Code
	CHANGE_SHOP_CODE_RS(3L), CHANGE_SHOP_CODE_DS(79L),
	ACTION_FORM_DATA_SEARCH(283L), ACTION_FORM_ADMIN(284L),
	LINK_EINFO(601L),
	USER_ADMIN(341L)
	;
	
	private Long functionId;
	
	private SvcFunctionCode(Long functionId) {
		this.functionId = functionId;
	}
	
	public Long getFunctionId() {
		return functionId;
	}

	public static SvcFunctionCode getFromId(Long functionId) {
		for (SvcFunctionCode function : SvcFunctionCode.values()) {
			if (functionId.equals(function.getFunctionId())) {
				return function;
			}
		}
		return null;
	}

}