package com.jaosn.gwtproject.shared.enums;

public enum SvcView {
	// before customer search
	CUST_SEARCH, PROSPECT_CUST_SEARCH, CUST_SEARCH_HIST, CALL_LOG_SEARCH, DFORM_MANAGEMENT,
	TEST_PAGE, UPDATE_PROFILE, CREATE_NEW_EMAIL, EMAIL_TEMPLATE_MANAGER, EMAIL_SENT_HISTORY,
	FAX_DOC_SEARCH, SMS_SEND_HISTORY, SMS_TEMPLATE_MANAGER,
	// after customer search
	CUST_OVERVIEW, IMS, LTS, MOB, CSL,
	CALL_NATURE_ADMIN, CREATE_NEW_SMS;
	
}
